name: Workflow1

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: self-hosted

    steps:
      - name: Workflow2
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_KEY }}
          repository: saikirangan/PGM02C_COB
          